apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask
spec:
  replicas: {{ .Values.flask.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-flask
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-flask
    spec:
      containers:
        - name: flask
          image: {{ .Values.flask.image }}
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD