apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:    #Deployment object owns this.
      app: nginx
  template:
    metadata:
      labels:
        app: nginx   # Pods created will carry this label.
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80