apiVersion: v1
kind: Service 
metadata:
  name: nginx-service-nodeport
spec:
  type: NodePort
  selector: # servie will forward request to pods matching the labels in this selector
    app: nginx
  ports:
    - port: 80 # Service Port
      targetPort: 80 # Container Port
      nodePort: 30080 # node port, application is accessed
      # on this port. <workernodeip>:<nodePort>
