apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP     # Cluster IP is default this line can be skipped. Oher options nodeport, load balancer
  selector:
    app: nginx    # service forwards traffic to pods with this label as defined in deployment file
  ports:
    - protocol: TCP
      port: 80   # Service port
      targetPort: 80 # Container port