apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-db
  template:
    metadata:
      labels:
        app: flask-db    # Service will forward request matching this label
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config   # config map's actual name
                  key: DB_NAME
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret   # secret's actual name 
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_ROOT_PASSWORD
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: init-sql
          configMap:
            name: db-init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: flask-db
spec:
  type: ClusterIP
  selector:
    app: flask-db
  ports:
    - port: 3306
      targetPort: 3306 
